export type UsageStatus = {
  planType: "FREE" | "STARTER" | "PRO" | "TEAM";
  billingType: "NONE" | "MONTHLY" | "YEARLY" | "CREDIT";
  planLabel: "free" | "boost" | "starter" | "pro" | "team";
  isBoostActive: boolean;
  boostEndsAt: string | null;
  boostDaysRemaining: number;
  dailyLimit: number;
  isUnlimitedDaily: boolean;
  dailyUsed: number;
  remaining: number;
  monthlyCreditLimit: number;
  monthlyCreditsUsed: number;
  monthlyCreditsRemaining: number;
  dailyCreditLimit: number;
  dailyCreditsUsed: number;
  dailyCreditsRemaining: number;
  paidCredits: number;
  bonusCredits: number;
  couponCreditBalance: number;
  couponCreditEndsAt: string | null;
  couponCreditActive: boolean;
  walletCreditsAvailable: number;
  planCreditsAvailable: number;
  totalCreditsAvailable: number;
  totalDailyCreditsAvailable: number;
  isCreditLimitReached: boolean;
  inputCharLimit: number;
  resultSaveLimit: number;
  shareDailyLimit: number;
  advancedReasoningDailyLimit: number;
  warningThresholdReached: boolean;
  isLimitReached: boolean;
  resetAt: string;
};

export type UsageErrorPayload = {
  error?: string;
  code?: "LIMIT_REACHED" | "INPUT_TOO_LONG" | "CREDIT_LIMIT_REACHED";
  redirectUrl?: string;
  usage?: UsageStatus;
};
